/**
 * The generated client, and the contract it is generated from (phase 11).
 *
 * plan/11 → *TS types + client generated from OpenAPI*, and *a contract test
 * fails if the OpenAPI schema drifts from what the UI expects*.
 *
 * Two different kinds of drift, so two tests. The first catches a contract that
 * has moved on without the types being regenerated — a backend route added and
 * a stale `api-types.ts` left behind. The second catches the opposite: the UI
 * asking for an endpoint the backend no longer publishes. Type-checking cannot
 * see the second one, because the path a screen fetches is only a string until
 * the client resolves it against `paths`.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';
import { describe, expect, it } from 'vitest';

import { ENDPOINTS } from './client';

// Resolved from the working directory rather than from `import.meta.url`: this
// file runs under jsdom, where a module URL is an http one and cannot be turned
// back into a path.
const CONTRACT = resolve(process.cwd(), '../contracts/openapi.json');
const TYPES = resolve(process.cwd(), '../contracts/api-types.ts');

/** What `openapi-typescript` writes above every file it generates. */
const BANNER = [
  '/**',
  ' * This file was auto-generated by openapi-typescript.',
  ' * Do not make direct changes to the file.',
  ' */',
  '',
].join('\n');

function contract(): OpenAPI3 & { paths: Record<string, Record<string, unknown>> } {
  return JSON.parse(readFileSync(CONTRACT, 'utf-8'));
}

describe('the generated client', () => {
  it('is generated from the committed contract, not from memory', async () => {
    const regenerated = astToString(await openapiTS(contract()));

    // The banner is the generator CLI's, not the emitter's; everything below it
    // is what the schema produces, and that is what must not have drifted.
    expect(readFileSync(TYPES, 'utf-8')).toBe(`${BANNER}\n${regenerated}`);
  });

  it('asks only for endpoints the contract declares', () => {
    const { paths } = contract();

    const missing = Object.values(ENDPOINTS).filter(
      ({ path, method }) => paths[path]?.[method] === undefined,
    );

    expect(missing).toEqual([]);
  });

  it('names one read per screen the plan describes', () => {
    // plan/11's core screens, by the read each of them opens with. Written out
    // here rather than derived from ENDPOINTS: a screen quietly dropped should
    // fail a test, and a list that read itself back never would.
    expect(Object.keys(ENDPOINTS)).toEqual(
      expect.arrayContaining([
        'projectState',
        'dashboard',
        'sourceWorkspace',
        'questions',
        'architecture',
        'articleWorkspace',
        'reviewHistory',
        'lineage',
        'trace',
        'inspectExecution',
        'compareExecutions',
        'job',
      ]),
    );
  });
});
