"""editorial domain schema

Revision ID: 0002_editorial
Revises: 0001_baseline
Create Date: 2026-07-24

The phase-02 domain backbone: the 17 editorial entities, the claim<->segment
association, and the content-addressed ``artifact_snapshots`` table. Enums are
non-native (VARCHAR + CHECK) so there is no Postgres native-enum type to migrate.
Autogenerated from the ORM models and reviewed; downgrade drops every table in
reverse-dependency order (plan/02 → migrations round-trip).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_editorial"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_snapshots',
    sa.Column('artifact_type', sa.Enum('source_document', 'source_model', 'content_architecture', 'article_concept', 'article_brief', 'article_version', 'review', 'revision_plan', 'voice_profile', 'validation_report', name='artifacttype', native_enum=False), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('content_location', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('parent_snapshot_id', sa.String(), nullable=True),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_snapshot_id'], ['artifact_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['voice_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_architectures',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['content_architectures.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_claims',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('classification', sa.Enum('directly_supported_fact', 'user_observation', 'interpretation', 'hypothesis', 'opinion', 'unknown', 'unsupported_claim', name='claimclassification', native_enum=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_gaps',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_concepts',
    sa.Column('architecture_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('angle', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['architecture_id'], ['content_architectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_versions',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['article_versions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['artifact_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_segments',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('gap_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gap_id'], ['source_gaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_briefs',
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('objectives', sa.String(), nullable=False),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['article_concepts.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['article_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('article_version_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_claim_segments',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['source_claims.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['source_segments.id'], ),
    sa.PrimaryKeyConstraint('claim_id', 'segment_id')
    )
    op.create_table('validation_reports',
    sa.Column('article_version_id', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('branch_status', sa.Enum('active', 'superseded', 'abandoned', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('selection_status', sa.Enum('pending', 'selected', 'rejected', name='selectionstatus', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['validation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_issues',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_plans',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_by_execution_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_plans')
    op.drop_table('review_issues')
    op.drop_table('validation_reports')
    op.drop_table('source_claim_segments')
    op.drop_table('reviews')
    op.drop_table('article_briefs')
    op.drop_table('user_answers')
    op.drop_table('source_segments')
    op.drop_table('article_versions')
    op.drop_table('article_concepts')
    op.drop_table('source_gaps')
    op.drop_table('source_documents')
    op.drop_table('source_claims')
    op.drop_table('content_architectures')
    op.drop_table('articles')
    op.drop_table('voice_profiles')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('artifact_snapshots')
    # ### end Alembic commands ###
