"""provenance execution records

Revision ID: 0003_provenance
Revises: 0002_editorial
Create Date: 2026-07-25

The phase-03 execution-provenance substrate: pipeline runs, stage executions,
the artefacts they consumed and produced, context selections, model and tool
invocations, decisions, evaluations, user interventions and the append-only
trace, plus the ExperimentRun/Job shells phases 12 and 09 fill in.

Two guarantees are carried by this migration rather than only by the ORM, so
that every deployed database has them:

- ``ck_decision_records_policy_version_present`` — a decision attributed to a
  policy must name the policy version (plan/03: no decision without decided_by
  and, for policy decisions, policy_version).
- ``uq_trace_events_correlation_seq`` — two events cannot claim the same
  position in one run's timeline.

Autogenerated from the ORM models and reviewed; downgrade drops every table in
reverse-dependency order.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import groundscribe.db


# revision identifiers, used by Alembic.
revision: str = "0003_provenance"
down_revision: str | Sequence[str] | None = "0002_editorial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_runs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=False),
    sa.Column('started_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('completed_at', groundscribe.db.UTCDateTime(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_executions',
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('parent_execution_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('started_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('completed_at', groundscribe.db.UTCDateTime(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['stage_executions.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_selections',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_records',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('decided_by_type', sa.Enum('user', 'model', 'policy', 'tool', 'system', name='actortype', native_enum=False), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('decided_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("decided_by_type <> 'policy' OR policy_version IS NOT NULL", name='ck_decision_records_policy_version_present'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_artifacts',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('input', 'output', name='artifactdirection', native_enum=False), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['artifact_snapshots.id'], ),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_invocations',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('parent_invocation_id', sa.String(), nullable=True),
    sa.Column('attempt_ordinal', sa.Integer(), nullable=False),
    sa.Column('retry_type', sa.Enum('network', 'rate_limit', 'provider_error', 'invalid_schema', 'content_repair', 'model_fallback', 'manual', 'prompt_modified', name='retrytype', native_enum=False), nullable=True),
    sa.Column('outcome', sa.Enum('accepted', 'invalid_json', 'invalid_schema', 'refused', 'timeout', 'provider_error', 'rate_limited', 'cancelled', name='invocationoutcome', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_version', sa.String(), nullable=False),
    sa.Column('request_snapshot_id', sa.String(), nullable=True),
    sa.Column('raw_response_snapshot_id', sa.String(), nullable=True),
    sa.Column('parsed_response_snapshot_id', sa.String(), nullable=True),
    sa.Column('validated_response_snapshot_id', sa.String(), nullable=True),
    sa.Column('started_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('completed_at', groundscribe.db.UTCDateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_invocation_id'], ['model_invocations.id'], ),
    sa.ForeignKeyConstraint(['parsed_response_snapshot_id'], ['artifact_snapshots.id'], ),
    sa.ForeignKeyConstraint(['raw_response_snapshot_id'], ['artifact_snapshots.id'], ),
    sa.ForeignKeyConstraint(['request_snapshot_id'], ['artifact_snapshots.id'], ),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.ForeignKeyConstraint(['validated_response_snapshot_id'], ['artifact_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_events',
    sa.Column('pipeline_run_id', sa.String(), nullable=True),
    sa.Column('stage_execution_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'model', 'policy', 'tool', 'system', name='actortype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('causation_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id', 'sequence', name='uq_trace_events_correlation_seq')
    )
    op.create_table('user_interventions',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('intervention_type', sa.Enum('approval', 'rejection', 'edit', 'override', 'answer', 'cancellation', name='interventiontype', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_items',
    sa.Column('context_selection_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('disposition', sa.Enum('selected', 'excluded', 'truncated', name='contextdisposition', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['context_selection_id'], ['context_selections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_invocations',
    sa.Column('stage_execution_id', sa.String(), nullable=False),
    sa.Column('model_invocation_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.Column('initiator', sa.Enum('model_selected', 'pipeline_mandated', name='toolinitiator', native_enum=False), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('raw_args', sa.JSON(), nullable=False),
    sa.Column('normalised_args', sa.JSON(), nullable=False),
    sa.Column('raw_result', sa.JSON(), nullable=False),
    sa.Column('normalised_result', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('started_at', groundscribe.db.UTCDateTime(), nullable=False),
    sa.Column('completed_at', groundscribe.db.UTCDateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_invocation_id'], ['model_invocations.id'], ),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_result_dependencies',
    sa.Column('tool_invocation_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['artifact_snapshots.id'], ),
    sa.ForeignKeyConstraint(['tool_invocation_id'], ['tool_invocations.id'], ),
    sa.PrimaryKeyConstraint('tool_invocation_id', 'snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_result_dependencies')
    op.drop_table('tool_invocations')
    op.drop_table('context_items')
    op.drop_table('user_interventions')
    op.drop_table('trace_events')
    op.drop_table('model_invocations')
    op.drop_table('execution_artifacts')
    op.drop_table('evaluation_runs')
    op.drop_table('decision_records')
    op.drop_table('context_selections')
    op.drop_table('stage_executions')
    op.drop_table('jobs')
    op.drop_table('pipeline_runs')
    op.drop_table('experiment_runs')
    # ### end Alembic commands ###
